name: Deploy MkDocs with mike

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch (mkdocs.yml must exist here)
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install mkdocs mike mkdocs-material

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy with mike
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ALIAS="latest"
          echo "Deploying version $VERSION"

          # Ensure we are in repo root (where mkdocs.yml lives)
          cd $GITHUB_WORKSPACE

          # Deploy versioned docs (mike handles gh-pages internally)
          mike deploy --push --update-aliases "$VERSION" "$ALIAS"
          mike set-default --push "$ALIAS"
