name: Deploy MkDocs with mike

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install mkdocs mike mkdocs-material

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # --- Fetch gh-pages and switch to it ---
      - name: Fetch and checkout gh-pages
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      # --- Deploy docs using mike ---
      - name: Deploy with mike
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ALIAS="latest"
          echo "Deploying version $VERSION"

          # Make sure we are at the repo root
          cd $GITHUB_WORKSPACE

          # Build versioned docs on gh-pages branch
          mike deploy --update-aliases "$VERSION" "$ALIAS"
          mike set-default "$ALIAS"

          # Force push updated gh-pages
          git add -A
          git commit -m "Deploy docs version $VERSION [skip ci]" || echo "Nothing to commit"
          git push origin gh-pages --force-with-lease

          # Update 'latest' alias if needed
          mike set-default "$ALIAS"
          git add -A
          git commit -m "Update latest alias to $ALIAS [skip ci]" || echo "Nothing to commit"
          git push origin gh-pages --force-with-lease
